<font face="Times New Roman" size="6">**Исследование сетевых параметров публичных DNS серверов**</font><br>

<font face="Times New Roman" size="4"><u>**Цель работы:**</u></font><br>
<font face="Times New Roman" size="4">Проанализировать сетевые параметры публичных DNS серверов, сделать мотивированный вывод о предпочтительных серверах</font><br><br>

<font face="Times New Roman" size="4"><u>**Исходные данные:**</u></font><br>
<font face="Times New Roman" size="3"><table>
| Устройство  | Виртуальная машина   | Операционная система| 
| ------------------------ | ------------------------- | --------------------|
| Asus X541U Vivobook PC   | VMware Workstation Pro 15 |  Windows 10         |
</table></font>
<font face="Times New Roman" size="5"><u>**Используемое ПО:**</u></font><br>

<font face="Times New Roman" size="4">1. Rstudio IDE</font><br>
<font face="Times New Roman" size="4">2. Traceroute/tracert</font><br>
<font face="Times New Roman" size="4">3. Ping</font><br>
<font face="Times New Roman" size="4">4. 2ip</font><br>


<font face="Times New Roman" size="5"><u>**Исследуемые провайдеры DNS**</u></font>

<font face="Times New Roman" size="4">1. Google Public DNS</font><br>
<font face="Times New Roman" size="4">2. Cloudflare DNS</font><br>
<font face="Times New Roman" size="4">3. OpenDNS</font><br>
<font face="Times New Roman" size="4">4. FLEX</font><br>


<font face="Times New Roman" size="5"><u>**Варианты решения задачи**</u></font>

<font face="Times New Roman" size="4">1. Использовать утилиту tracert/traceroute(выберем этот вариант)</font><br>
<font face="Times New Roman" size="4">2. Использовать ручной поиск, без утилит</font><br>


<font face="Times New Roman" size="5"><u>**Общий план выполнения**</u></font>

<font face="Times New Roman" size="4">1. По исследуемым серверам собрать следующие данные:</font><br>
<font face="Times New Roman" size="4">1.1.маршрут</font><br>
<font face="Times New Roman" size="4">1.2.местоположение каждого узла маршрута к DNS-серверу</font><br>
<font face="Times New Roman" size="4">1.3.организацию, владеющую каждым узлом маршрута к DNS-серверу</font><br>
<font face="Times New Roman" size="4">1.4.среднюю RTT (round trip time) к DNS-серверу</font><br>
<font face="Times New Roman" size="4">2. Выделить те узлы маршрута, которые вносят наибольшую временную задержку при передаче</font><br>
<font face="Times New Roman" size="4">3. Сравнить сетевые параметры DNS серверов</font><br>

<font face="Times New Roman" size="5"><u>**Ход работы**</u></font>

<font face="Times New Roman" size="4"><u>**1.Google Public DNS**</u></font><br>
<font face="Times New Roman" size="3"><u>**Маршрут:**</u></font><br>


```
 >tracert 8.8.8.8

Трассировка маршрута к dns.google [8.8.8.8]
с максимальным числом прыжков 30:

  1     3 ms    <1 мс    <1 мс  192.168.1.1
  2     2 ms     3 ms     2 ms  l2tp.flex.ru [10.255.255.254]
  3     4 ms     4 ms     3 ms  94.253.0.4
  4     6 ms     4 ms     5 ms  94.253.0.170
  5   132 ms     4 ms     4 ms  209.85.173.244
  6    49 ms     8 ms    31 ms  108.170.250.51
  7   112 ms    22 ms    22 ms  216.239.50.44
  8    18 ms    19 ms    18 ms  216.239.43.20
  9     *      119 ms    19 ms  216.239.47.165
 10     *        *        *     Превышен интервал ожидания для запроса.
 11     *        *        *     Превышен интервал ожидания для запроса.
 12     *        *        *     Превышен интервал ожидания для запроса.
 13     *        *        *     Превышен интервал ожидания для запроса.
 14     *        *        *     Превышен интервал ожидания для запроса.
 15     *        *        *     Превышен интервал ожидания для запроса.
 16     *        *        *     Превышен интервал ожидания для запроса.
 17     *        *        *     Превышен интервал ожидания для запроса.
 18     *        *        *     Превышен интервал ожидания для запроса.
 19    18 ms    18 ms    18 ms  dns.google [8.8.8.8]

Трассировка завершена.

```
<font face="Times New Roman" size="3"><u>**Среднее RTT:**</u></font><br>
```
>ping 8.8.8.8

Обмен пакетами с 8.8.8.8 по с 32 байтами данных:
Ответ от 8.8.8.8: число байт=32 время=109мс TTL=46
Ответ от 8.8.8.8: число байт=32 время=166мс TTL=46
Ответ от 8.8.8.8: число байт=32 время=118мс TTL=46
Ответ от 8.8.8.8: число байт=32 время=121мс TTL=46

Статистика Ping для 8.8.8.8:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 109мсек, Максимальное = 166 мсек, Среднее = 128 мсек
  
```
<font face="Times New Roman" size="3">Наибольшая временная задержка у 2го узла</font><br>

<font face="Times New Roman" size="3"><u>**Местоположение и организация:**</u></font><br>

<font face="Times New Roman" size="4"><table>
|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      Россия, Ногинск        |   Роутер    | 
|  2   |l2tp.flex.ru [10.255.255.254]|     Лос-Анжелес, США       |    IANA     |  
|  3   | 94.253.0.4 |     Россия, Москва       |Flex|
|  4 | 94.253.0.170  |   Россия, Москва      | Flex | 
|  5     |          209.85.173.244                 |США, Калифорния, Маунтин| Google LLC  | 
|  6    |          108.170.250.51                  |США, Калифорния, Маунтин| Google LLC  | 
|  7    |         216.239.50.44                 |Англия| Google LLC  | 
|  8     |         216.239.43.20                   |США, Эмеривилл| Google LLC  |   
|  9  |        216.239.47.165               |   США, Эмеривилл                         |      Google LLC       |
|  10   |        Request timed out.               |                            |             |    
|  11 |        Request timed out.               |                            |             |           
|  12    |        Request timed out.               |                            |             |       
|  13 |            Request timed out.               |                            |             |      
|  14      |        Request timed out.               |                            |             |   
|  15| Request timed out.               |                            |             |          
|  16   |        Request timed out.               |                            |             |      
|  17    |        Request timed out.               |                            |             |      
|  18   |       dns.google [8.8.8.8]              |       США, Нью-Йорк        | Google LLC  |    
</table></font>

<font face="Times New Roman" size="4"><u>**2.OpenDNS**</u></font><br>
<font face="Times New Roman" size="3"><u>**Маршрут:**</u></font><br>


```
>tracert 208.67.222.222

Трассировка маршрута к resolver1.opendns.com [208.67.222.222]
с максимальным числом прыжков 30:

  1     1 ms     1 ms    <1 мс  192.168.1.1
  2    99 ms     2 ms     2 ms  l2tp.flex.ru [10.255.255.254]
  3     5 ms     6 ms     6 ms  94.253.0.4
  4     5 ms     4 ms     4 ms  noginsk-dc.moscow.flex.ru [80.252.128.72]
  5     5 ms     7 ms     5 ms  ae21.RT.MR.MSK.RU.retn.net [87.245.228.89]
  6   151 ms    51 ms    51 ms  ae10-11.RT.THV.PAR.FR.retn.net [87.245.232.252]
  7    50 ms    50 ms    49 ms  opendns.par.franceix.net [37.49.236.210]
  8    50 ms    50 ms    50 ms  resolver1.opendns.com [208.67.222.222]

Трассировка завершена.

```
<font face="Times New Roman" size="3"><u>**Среднее RTT:**</u></font><br>
```
>ping 208.67.222.222

Обмен пакетами с 208.67.222.222 по с 32 байтами данных:
Ответ от 208.67.222.222: число байт=32 время=50мс TTL=57
Ответ от 208.67.222.222: число байт=32 время=49мс TTL=57
Ответ от 208.67.222.222: число байт=32 время=49мс TTL=57
Ответ от 208.67.222.222: число байт=32 время=49мс TTL=57

Статистика Ping для 208.67.222.222:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 49мсек, Максимальное = 50 мсек, Среднее = 49 мсек
```
<font face="Times New Roman" size="3">Наибольшая временная задержка у 1го узла</font><br>

<font face="Times New Roman" size="3"><u>**Местоположение и организация:**</u></font><br>

<font face="Times New Roman" size="4"><table>
|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      Россия, Ногинск        |   Роутер    | 
|  2   |l2tp.flex.ru [10.255.255.254]|     Лос-Анжелес, США       |    IANA     |  
|  3   | 94.253.0.4 |     Россия, Москва       |Flex|
|  4 | noginsk-dc.moscow.flex.ru [80.252.128.72]  |   Россия, Ногинск      | Flex | 
|  5     |          ae21.RT.MR.MSK.RU.retn.net [87.245.228.89]                 |Россия, Москва| ReTN  | 
|  6    |          ae10-11.RT.THV.PAR.FR.retn.net [87.245.232.252]                  |США| ReTN's Backbone  | 
|  7    |        opendns.par.franceix.net [37.49.236.210]                 |Франция, Париж| FranceIX Paris Peering LAN  | 
|  8     |         resolver1.opendns.com [208.67.222.222]                  |США, Сан-Франциско| 	Cisco OpenDNS, LLC  |   

</table></font>

<font face="Times New Roman" size="4"><u>**3.Cloudflare DNS**</u></font><br>
<font face="Times New Roman" size="3"><u>**Маршрут:**</u></font><br>


```
>tracert 1.1.1.1

Трассировка маршрута к one.one.one.one [1.1.1.1]
с максимальным числом прыжков 30:

  1    56 ms     1 ms     1 ms  192.168.1.1
  2     4 ms     2 ms     3 ms  l2tp.flex.ru [10.255.255.254]
  3     5 ms     4 ms     9 ms  94.253.0.4
  4     5 ms     5 ms     4 ms  10.1.0.5
  5     5 ms     5 ms     8 ms  zapret-service [80.252.130.132]
  6     6 ms     5 ms     7 ms  zapret-service.m9.moscow.flex.ru [80.252.130.129]
  7     9 ms     7 ms     8 ms  msk-ix.cloudflare.com [195.208.209.7]
  8     6 ms     5 ms     5 ms  one.one.one.one [1.1.1.1]

Трассировка завершена.

```
<font face="Times New Roman" size="3"><u>**Среднее RTT:**</u></font><br>
```
>ping 1.1.1.1

Обмен пакетами с 1.1.1.1 по с 32 байтами данных:
Ответ от 1.1.1.1: число байт=32 время=5мс TTL=59
Ответ от 1.1.1.1: число байт=32 время=5мс TTL=59
Ответ от 1.1.1.1: число байт=32 время=5мс TTL=59
Ответ от 1.1.1.1: число байт=32 время=5мс TTL=59

Статистика Ping для 1.1.1.1:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 5мсек, Максимальное = 5 мсек, Среднее = 5 мсек
```
<font face="Times New Roman" size="3">Наибольшая временная задержка не выявлена</font><br>

<font face="Times New Roman" size="3"><u>**Местоположение и организация:**</u></font><br>

<font face="Times New Roman" size="4"><table>
|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      Россия, Ногинск        |   Роутер    | 
|  2   |l2tp.flex.ru [10.255.255.254]|     Лос-Анжелес, США       |    IANA     |  
|  3   | 94.253.0.4 |     Россия, Москва       |Flex|
|  4 | 10.1.0.5  |   Лос-Анжелес, США      | 	Internet Assigned Numbers Authority | 
|  5     |          zapret-service [80.252.130.132]                 |Россия, Ногинск| Flex  | 
|  6    |          zapret-service.m9.moscow.flex.ru [80.252.130.129]                  |Россия, Ногинск| Flex  | 
|  7    |        msk-ix.cloudflare.com [195.208.209.7]                 |Россия, Москва| - | 
|  8     |         one.one.one.one [1.1.1.1]                  |Австралия|APNIC and Cloudflare DNS Resolver project 	  |   

</table></font>


<font face="Times New Roman" size="4"><u>**4.Flex**</u></font><br>
<font face="Times New Roman" size="3"><u>**Маршрут:**</u></font><br>


```
>tracert 80.252.130.253

Трассировка маршрута к ns3.flex.ru [80.252.130.253]
с максимальным числом прыжков 30:

  1     1 ms    <1 мс    <1 мс  192.168.1.1
  2     2 ms     2 ms     1 ms  l2tp.flex.ru [10.255.255.254]
  3     4 ms     4 ms     3 ms  94.253.0.4
  4     4 ms     3 ms     2 ms  ns3.flex.ru [80.252.130.253]

Трассировка завершена.

```
<font face="Times New Roman" size="3"><u>**Среднее RTT:**</u></font><br>
```
>ping 80.252.130.253

Обмен пакетами с 80.252.130.253 по с 32 байтами данных:
Ответ от 80.252.130.253: число байт=32 время=4мс TTL=61
Ответ от 80.252.130.253: число байт=32 время=4мс TTL=61
Ответ от 80.252.130.253: число байт=32 время=3мс TTL=61
Ответ от 80.252.130.253: число байт=32 время=5мс TTL=61

Статистика Ping для 80.252.130.253:
    Пакетов: отправлено = 4, получено = 4, потеряно = 0
    (0% потерь)
Приблизительное время приема-передачи в мс:
    Минимальное = 3мсек, Максимальное = 5 мсек, Среднее = 4 мсек
```
<font face="Times New Roman" size="3">Наибольшая временная задержка на 5м узле.</font><br>

<font face="Times New Roman" size="3"><u>**Местоположение и организация:**</u></font><br>

<font face="Times New Roman" size="4"><table>
|  №    |              Узел                       |     Местоположение      |Организация  |
|:---:|:-----------:|:-----------:|:-----------:|:---------------------------------------:|:--------------------------:|:-----------:|:---------:|:-----------------------------------------------:|
|  1  |          192.168.1.1                    |      Россия, Ногинск        |   Роутер    | 
|  2   |l2tp.flex.ru [10.255.255.254]|     Лос-Анжелес, США       |    IANA     |  
|  3   | 94.253.0.4 |     Россия, Москва       |Flex|
|  4 | 80.252.130.253  |   Россия, Ногинск      | 	Flex | 


</table></font>

<font face="Times New Roman" size="5"><u>**Сравнительная диаграмма**</u></font>


<font face="Times New Roman" size="5"><u>Используемые цвета:</u></font>

<font face="Times New Roman" size="4">1. Google DNS - красный</font><br>
<font face="Times New Roman" size="4">2. Cloudflare DNS - зеленый</font><br>
<font face="Times New Roman" size="4">3. OpenDNS - желтый </font><br>
<font face="Times New Roman" size="4">4. Кварц-телеком - голубой</font><br>

```{r, echo=FALSE}
x <- c(0,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125,130)
y <- c(0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10,10.5,11,11.5,12,12.5,13)
x_1 <- c(109,166,118,121)
y_1 <- c(1,2,3,4)
x_2 <- c(50,49,49,49)
y_2 <- c(1,2,3,4)
x_3 <- c(5,5,5,5)
y_3 <- c(1,2,3,4)
x_4 <- c(4,4,3,5)
y_4 <- c(1,2,3,4)

plot(y,x,main = "Сравнительная диаграмма RTT к серверам", xlab = "Step", ylab = "RTT",type = "n")
points(y_1,x_1, col = "black")
lines(y_1,x_1, col = "black")
points(y_2,x_2, col = "green")
lines(y_2,x_2, col = "green")
points(y_3,x_3, col = "orange")
lines(y_3,x_3, col = "orange")
points(y_4,x_4, col = "blue")
lines(y_4,x_4, col = "blue")
```


<font face="Times New Roman" size="5"><u>**Оценка результатов:**</u></font><br>
<font face="Times New Roman" size="4">Меньше всего времени потребовалось для обмена пакетов для FLEX и Cloudflare DNS.</font><br>


<font face="Times New Roman" size="5"><u>**Вывод:**</u></font><br>
<font face="Times New Roman" size="4">Я познакомилась с DNS серверами,проанализировала их и научилась пользоваться утилитой tracert.</font><br>


